package org.farrukh.mirza.pdf.service;

import org.apache.commons.lang3.StringEscapeUtils;

import java.util.HashMap;

public class StringEscapeHelpers {
    private static final HashMap<Character, String> htmlEncodeChars = new HashMap<Character, String>() {{
        put('Œ', "&OElig;");
        put('œ', "&oelig;");
        put('Š', "&Scaron;");
        put('š', "&scaron;");
        put('Ÿ', "&Yuml;");
        put('ˆ', "&circ;");
        put('˜', "&tilde;");
        put('\u2002', "&ensp;");
        put('\u2003', "&emsp;");
        put('\u2009', "&thinsp;");
        put('\u200C', "&zwnj;");
        put('\u200D', "&zwj;");
        put('\u200E', "&lrm;");
        put('\u200F', "&rlm;");
        put('–', "&ndash;");
        put('—', "&mdash;");
        put('‘', "&lsquo;");
        put('’', "&rsquo;");
        put('‚', "&sbquo;");
        put('“', "&ldquo;");
        put('”', "&rdquo;");
        put('„', "&bdquo;");
        put('†', "&dagger;");
        put('‡', "&Dagger;");
        put('‰', "&permil;");
        put('‹', "&lsaquo;");
        put('›', "&rsaquo;");
        put('€', "&euro;");

        // Character entity references for ISO 8859-1 characters
        put('\u00A0', "&nbsp;");
        put('¡', "&iexcl;");
        put('¢', "&cent;");
        put('£', "&pound;");
        put('¤', "&curren;");
        put('¥', "&yen;");
        put('¦', "&brvbar;");
        put('§', "&sect;");
        put('¨', "&uml;");
        put('©', "&copy;");
        put('ª', "&ordf;");
        put('«', "&laquo;");
        put('¬', "&not;");
        put('\u00AD', "&shy;");
        put('®', "&reg;");
        put('¯', "&macr;");
        put('°', "&deg;");
        put('±', "&plusmn;");
        put('²', "&sup2;");
        put('³', "&sup3;");
        put('´', "&acute;");
        put('µ', "&micro;");
        put('¶', "&para;");
        put('·', "&middot;");
        put('¸', "&cedil;");
        put('¹', "&sup1;");
        put('º', "&ordm;");
        put('»', "&raquo;");
        put('¼', "&frac14;");
        put('½', "&frac12;");
        put('¾', "&frac34;");
        put('¿', "&iquest;");
        put('À', "&Agrave;");
        put('Á', "&Aacute;");
        put('Â', "&Acirc;");
        put('Ã', "&Atilde;");
        put('Ä', "&Auml;");
        put('Å', "&Aring;");
        put('Æ', "&AElig;");
        put('Ç', "&Ccedil;");
        put('È', "&Egrave;");
        put('É', "&Eacute;");
        put('Ê', "&Ecirc;");
        put('Ë', "&Euml;");
        put('Ì', "&Igrave;");
        put('Í', "&Iacute;");
        put('Î', "&Icirc;");
        put('Ï', "&Iuml;");
        put('Ð', "&ETH;");
        put('Ñ', "&Ntilde;");
        put('Ò', "&Ograve;");
        put('Ó', "&Oacute;");
        put('Ô', "&Ocirc;");
        put('Õ', "&Otilde;");
        put('Ö', "&Ouml;");
        put('×', "&times;");
        put('Ø', "&Oslash;");
        put('Ù', "&Ugrave;");
        put('Ú', "&Uacute;");
        put('Û', "&Ucirc;");
        put('Ü', "&Uuml;");
        put('Ý', "&Yacute;");
        put('Þ', "&THORN;");
        put('ß', "&szlig;");
        put('à', "&agrave;");
        put('á', "&aacute;");
        put('â', "&acirc;");
        put('ã', "&atilde;");
        put('ä', "&auml;");
        put('å', "&aring;");
        put('æ', "&aelig;");
        put('ç', "&ccedil;");
        put('è', "&egrave;");
        put('é', "&eacute;");
        put('ê', "&ecirc;");
        put('ë', "&euml;");
        put('ì', "&igrave;");
        put('í', "&iacute;");
        put('î', "&icirc;");
        put('ï', "&iuml;");
        put('ð', "&eth;");
        put('ñ', "&ntilde;");
        put('ò', "&ograve;");
        put('ó', "&oacute;");
        put('ô', "&ocirc;");
        put('õ', "&otilde;");
        put('ö', "&ouml;");
        put('÷', "&divide;");
        put('ø', "&oslash;");
        put('ù', "&ugrave;");
        put('ú', "&uacute;");
        put('û', "&ucirc;");
        put('ü', "&uuml;");
        put('ý', "&yacute;");
        put('þ', "&thorn;");
        put('ÿ', "&yuml;");

        // Mathematical, Greek and Symbolic characters for HTML
        put('ƒ', "&fnof;");
        put('Α', "&Alpha;");
        put('Β', "&Beta;");
        put('Γ', "&Gamma;");
        put('Δ', "&Delta;");
        put('Ε', "&Epsilon;");
        put('Ζ', "&Zeta;");
        put('Η', "&Eta;");
        put('Θ', "&Theta;");
        put('Ι', "&Iota;");
        put('Κ', "&Kappa;");
        put('Λ', "&Lambda;");
        put('Μ', "&Mu;");
        put('Ν', "&Nu;");
        put('Ξ', "&Xi;");
        put('Ο', "&Omicron;");
        put('Π', "&Pi;");
        put('Ρ', "&Rho;");
        put('Σ', "&Sigma;");
        put('Τ', "&Tau;");
        put('Υ', "&Upsilon;");
        put('Φ', "&Phi;");
        put('Χ', "&Chi;");
        put('Ψ', "&Psi;");
        put('Ω', "&Omega;");
        put('α', "&alpha;");
        put('β', "&beta;");
        put('γ', "&gamma;");
        put('δ', "&delta;");
        put('ε', "&epsilon;");
        put('ζ', "&zeta;");
        put('η', "&eta;");
        put('θ', "&theta;");
        put('ι', "&iota;");
        put('κ', "&kappa;");
        put('λ', "&lambda;");
        put('μ', "&mu;");
        put('ν', "&nu;");
        put('ξ', "&xi;");
        put('ο', "&omicron;");
        put('π', "&pi;");
        put('ρ', "&rho;");
        put('ς', "&sigmaf;");
        put('σ', "&sigma;");
        put('τ', "&tau;");
        put('υ', "&upsilon;");
        put('φ', "&phi;");
        put('χ', "&chi;");
        put('ψ', "&psi;");
        put('ω', "&omega;");
        put('ϑ', "&thetasym;");
        put('ϒ', "&upsih;");
        put('ϖ', "&piv;");
        put('•', "&bull;");
        put('…', "&hellip;");
        put('′', "&prime;");
        put('″', "&Prime;");
        put('‾', "&oline;");
        put('⁄', "&frasl;");
        put('℘', "&weierp;");
        put('ℑ', "&image;");
        put('ℜ', "&real;");
        put('™', "&trade;");
        put('ℵ', "&alefsym;");
        put('←', "&larr;");
        put('↑', "&uarr;");
        put('→', "&rarr;");
        put('↓', "&darr;");
        put('↔', "&harr;");
        put('↵', "&crarr;");
        put('⇐', "&lArr;");
        put('⇑', "&uArr;");
        put('⇒', "&rArr;");
        put('⇓', "&dArr;");
        put('⇔', "&hArr;");
        put('∀', "&forall;");
        put('∂', "&part;");
        put('∃', "&exist;");
        put('∅', "&empty;");
        put('∇', "&nabla;");
        put('∈', "&isin;");
        put('∉', "&notin;");
        put('∋', "&ni;");
        put('∏', "&prod;");
        put('∑', "&sum;");
        put('−', "&minus;");
        put('∗', "&lowast;");
        put('√', "&radic;");
        put('∝', "&prop;");
        put('∞', "&infin;");
        put('∠', "&ang;");
        put('∧', "&and;");
        put('∨', "&or;");
        put('∩', "&cap;");
        put('∪', "&cup;");
        put('∫', "&int;");
        put('∴', "&there4;");
        put('∼', "&sim;");
        put('≅', "&cong;");
        put('≈', "&asymp;");
        put('≠', "&ne;");
        put('≡', "&equiv;");
        put('≤', "&le;");
        put('≥', "&ge;");
        put('⊂', "&sub;");
        put('⊃', "&sup;");
        put('⊄', "&nsub;");
        put('⊆', "&sube;");
        put('⊇', "&supe;");
        put('⊕', "&oplus;");
        put('⊗', "&otimes;");
        put('⊥', "&perp;");
        put('⋅', "&sdot;");
        put('⌈', "&lceil;");
        put('⌉', "&rceil;");
        put('⌊', "&lfloor;");
        put('⌋', "&rfloor;");
        put('〈', "&lang;");
        put('〉', "&rang;");
        put('◊', "&loz;");
        put('♠', "&spades;");
        put('♣', "&clubs;");
        put('♥', "&hearts;");
        put('♦', "&diams;");
    }};


    public static String escapeHtml4WithoutSpecialCharacters(String input) {
        if (input == null) {
            return null;
        }

        StringBuilder output = new StringBuilder();

        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);

            if (htmlEncodeChars.containsKey(c)) {
                output.append(c);
            } else {
                output.append(StringEscapeUtils.escapeHtml4(Character.toString(c)));
            }
        }

        return output.toString();
    }
}
